name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install project dependencies
        run: |
          pip install poetry
          poetry install
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          poetry run coverage run -m unittest discover ./app/tests/
          poetry run coverage report
          poetry run coverage xml
        working-directory: ${{ github.workspace }}

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
